name: Caching artifacts

on:
  - workflow_dispatch

jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.11.1
      - name: Cache node modules
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: "npm-cache"
      - name: Display cache output
        run: echo ${{ steps.cache-deps.outputs }}
      - name: Install dependencies
        run: npm install
      - name: Use axios
        uses: actions/github-script@v8
        with:
          script: |
            const axios = require('axios');
            const response = await axios.get('https://api.github.com');
            console.log(response.data);
