name: Caller workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name to greet"
        type: string
        required: true

jobs:
  call-reusable:
    uses: .github/workflows/reusable.yml
    with:
      name: ${{ inputs.name }}
  print-greeting:
    runs-on: ubuntu-latest
    needs: call-reusable
    steps:
      - run: |
          echo "Greeting from outputs: ${{ needs.call-reusable.outputs.greeting }}"
