name: Expressions
run-name: "Expressions & Contexts by @${{ github.actor }}, event: ${{ github.event_name }}"

on:
  - push
  - pull_request
  - issues
  - workflow_dispatch

jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo $(( 1 + 1 ))
          echo ${{ 1 > 2 }}
      - name: Conditional step
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo ${{ github.event_name }}
