name: Expressions

on:
  - push
  - pull_request
  - issues
  - workflow_dispatch

jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo $(( 1 + 1 ))
          echo ${{ 1 > 2 }}
      - name: Dump context
        run: |
          echo github ${{ toJson(github) }}
          echo job ${{ toJson(job)}}
          echo runner ${{ toJson(runner)}}
          echo steps ${{ toJson(steps)}}
          echo strategy ${{ toJson(strategy)}}
          echo matrix ${{ toJson(matrix)}}
          echo env ${{ toJson(env)}}
          echo secrets ${{ toJson(secrets)}}
          echo inputs ${{ toJson(inputs)}}
