name: First Workflow

on: push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Run a shell command
        run: echo "Hello, world!"
      - name: Multiline shell command
        run: |
          echo "First line"
          echo "Second line"
          echo "Third line"
