name: First Workflow

on:
  - workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.11.1
          cache: "pnpm"
      - name: Prepare
        run: pnpm run prepare
      - name: Run linter
        run: pnpm run lint
      - name: Erroring step
        continue-on-error: true
        run: exit 1
      - name: After erroring step
        run: echo "After erroring step"
  lint-success:
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ !cancelled() }}
    steps:
      - name: Lint success
        if: ${{ contains(needs.*.result, 'failure') }}
        run: |
          echo "I am catching the failure: ${{ needs.lint.result }}"
