name: Level Vars

on:
  - push

jobs:
  level-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Log level vars
        run: |
          echo "ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}"
          echo "REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}"
