name: Manual Checkout

on:
  - push

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: ls -a
      - name: Checkout code
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List files
        run: ls -a
      - name: Run linter
        run: pnpm run lint
