name: Reusable

on:
  workflow_call:
    inputs:
      name:
        description: "Name to greet"
        type: string
        required: true
    outputs:
      greeting:
        description: "Greeting message"
        value: ${{ jobs.greet.outputs.greeting }}

jobs:
  greet:
    runs-on: ubuntu-latest
    outputs:
      # This line must be a direct key-value pair
      greeting: ${{ steps.set-output.outputs.greeting }}
    steps:
      - name: Set output
        id: set-output
        run: echo "greeting=Hello, ${{ inputs.name }}!" >> $GITHUB_OUTPUT
