name: Status Check

on:
  - push

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep step
        run: sleep 20
      - name: Erroring step
        run: exit 1
      - name: Post erroring step
        if: failure()
        run: echo "Post erroring step"
      - name: Runs on success
        if: success()
        run: echo "Runs on success"
      - name: Always runs
        if: always()
        run: echo "Always runs"
      - name: Runs on cancellation
        if: cancelled()
        run: echo "Runs on cancellation"
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - name: Post failure
        run: echo "Post failure job-2"
