name: Workflow run

on:
  workflow_run:
    workflows: [Labeled]
    types: [completed]

jobs:
  workflow-run:
    runs-on: ubuntu-latest
    steps:
      - name: Run workflow
        run: echo "I was triggered by a workflow run of ${{ github.workflow }}"
